version: "3.7"

services:
    database:
        image: postgres
        container_name: deliveryDatabase
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=delivery
            - POSTGRES_DB=deliveryDB
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local
